spring.application.name=ecommerce-backend
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

razorpay.key.id=rzp_test_Td4yttQpz8mQrF
razorpay.key.secret=ceWLFE2056K2kN7Hr3wy7WM0
razorpay.webhook.secret=SmartCartWebhook@2026#KLU

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kodavalilakshminarayana@gmail.com
spring.mail.password=woui rxuj qbuz dfns
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

smartcart.mail.from=kodavalilakshminarayana@gmail.com

